spring:
  datasource:
    driverClassName: com.mysql.cj.jdbc.Driver
    url:  jdbc:mysql://localhost:3306/test?serverTimezone=GMT&characterEncoding=utf8
    username: root
    password: 123456

mybatis:
  mapper-locations: classpath:mybatis/*.xml
  configuration:
    call-setters-on-nulls: true
    map-underscore-to-camel-case: true

server:
  port: 9999